In [3]:
import numpy as np #industry standard

#### Use the following code for the questions below:

In [4]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

#### How many negative numbers are there?

In [19]:
mask = a < 0
mask

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [24]:
new_array = a[mask]
new_array

array([-2, -1, -6, -7])

In [25]:
len(new_array)

4

In [26]:
(a<0).sum()

4

#### How many positive numbers are there?

In [30]:
len(a[a > 0])

5

In [34]:
(a > 0).sum()

5

#### How many even positive numbers are there?

In [40]:
mask = (a % 2 == 0) & (a > 0) #have to use & since we are comparing two arrays
mask

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False])

In [41]:
a[mask]

array([ 4, 10, 12])

#### If you were to add 3 to each data point, how many positive numbers would there be?

In [58]:
((a + 3) > 0).sum()

10

In [59]:
(a+3) [(a + 3) > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [60]:
len((a+3) [(a + 3) > 0])

10

#### If you squared each number, what would the new mean and standard deviation be?

In [63]:
a_squared = a ** 2
a_squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [65]:
a_squared.mean()

74.0

In [66]:
a_squared.std()

144.0243035046516

#### A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [67]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [68]:
a.mean()

3.0

In [70]:
a_centered = a - (a.mean())
a_centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [71]:
a_centered.mean()

0.0

#### Calculate the z-score for each data point. Recall that the z-score is given by:

Z = (x - $\mu$) / $\sigma$ #latex in markdown

$\mu$:mean 

$\sigma$: standard deviation

In [74]:
(a - a.mean()) / a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

### Setup 1

Use python's built in functionality/operators to determine the following:

In [75]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [76]:
sum(a)

55

#### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [77]:
min(a)

1

#### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [78]:
max(a)

10

#### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [83]:
sum(a) / len(a)

5.5

#### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [89]:
product_of_a = 1

for i in a:
    product_of_a *= i
    
product_of_a

3628800

#### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [94]:
squares_of_a = []

for i in a:
#     print(i**2)
    squares_of_a.append(i**2)

squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

#### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [98]:
odds_in_a = []

for i in a:
    if i % 2 == 1:
#         print(i)
        odds_in_a.append(i)
        
odds_in_a

[1, 3, 5, 7, 9]

#### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [102]:
evens_in_a = []

for i in a:
    if i % 2 == 0:
#         print(i)
        evens_in_a.append(i)
    
evens_in_a

[2, 4, 6, 8, 10]

### Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [105]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b

[[3, 4, 5], [6, 7, 8]]

In [106]:
b = np.array(b)

#### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 

In [ ]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [111]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [108]:
np.sum(b)

33

In [109]:
b.sum()

33

In [112]:
sum(sum(b))

33

#### Exercise 2 - refactor the following to use numpy. 

In [113]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [114]:
np.min(b)

3

#### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [115]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [116]:
np.max(b)

8

#### Exercise 4 - refactor the following using numpy to find the mean of b

In [ ]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [117]:
np.mean(b)

5.5

#### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [118]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [119]:
np.prod(b)

20160

#### Exercise 6 - refactor the following to use numpy to find the list of squares 

In [ ]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [121]:
np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [122]:
b ** 2

array([[ 9, 16, 25],
       [36, 49, 64]])

#### Exercise 7 - refactor using numpy to determine the odds_in_b

In [ ]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [126]:
b [b % 2 == 1]

array([3, 5, 7])

#### Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [ ]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [127]:
b [b % 2 == 0]

array([4, 6, 8])

#### Exercise 9 - print out the shape of the array b.

In [130]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [131]:
b.shape #rows vs cols

(2, 3)

#### Exercise 10 - transpose the array b.

In [135]:
np.transpose(b) #numpy function

array([[3, 6],
       [4, 7],
       [5, 8]])

In [136]:
np.transpose(b).shape

(3, 2)

In [137]:
b.T #method

array([[3, 6],
       [4, 7],
       [5, 8]])

#### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [138]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [139]:
np.reshape(b, (1,6))

array([[3, 4, 5, 6, 7, 8]])

In [140]:
b.flatten()

array([3, 4, 5, 6, 7, 8])

#### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [142]:
np.reshape(b, (6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Setup 3

In [143]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [145]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Exercise 1 - Find the min, max, sum, and product of c.

In [148]:
c.min(), c.max(), c.sum(), c.prod()

(1, 9, 45, 362880)

#### Exercise 2 - Determine the standard deviation of c.

In [149]:
c.std()

2.581988897471611

#### Exercise 3 - Determine the variance of c.

In [150]:
c.var()

6.666666666666667

#### Exercise 4 - Print out the shape of the array c

In [154]:
c.shape #attribute

(3, 3)

#### Exercise 5 - Transpose c and print out transposed result.

In [157]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Exercise 6 - Get the dot product of the array c with c. 

In [161]:
c*c #not a dot product

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [162]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

#### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [168]:
(c.T * c)

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [169]:
(c.T * c).sum()

261

#### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [170]:
(c.T * c)

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [171]:
(c.T * c).prod()

131681894400

### Setup 4

In [204]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d

[[90, 30, 45, 0, 120, 180],
 [45, -90, -30, 270, 90, 0],
 [60, 45, -45, 90, -45, 180]]

In [205]:
d = np.array(d)
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

#### Exercise 1 - Find the sine of all the numbers in d

In [175]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

#### Exercise 2 - Find the cosine of all the numbers in d

In [176]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

#### Exercise 3 - Find the tangent of all the numbers in d

In [177]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

#### Exercise 4 - Find all the negative numbers in d

In [181]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [180]:
d [d < 0]

array([-90, -30, -45, -45])

#### Exercise 5 - Find all the positive numbers in d

In [186]:
mask = d > 0

In [187]:
d [mask]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

#### Exercise 6 - Return an array of only the unique numbers in d.

In [188]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [197]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

#### Exercise 7 - Determine how many unique numbers there are in d.

In [198]:
# np.count_nonzero(np.unique(d)) #dont use this

In [199]:
len(np.unique(d))

11

#### Exercise 8 - Print out the shape of d.

In [200]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [206]:
d.shape

(3, 6)

#### Exercise 9 - Transpose and then print out the shape of d.

In [209]:
d.T

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [208]:
d.T.shape

(6, 3)

#### Exercise 10 - Reshape d into an array of 9 x 2

In [210]:
np.reshape(d, (9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])